# obj: main.o
# Create by pipi

CPL  = D:/cygwin/bin/
CPP  = $(CPL)g++.exe
ACXXFLAGS =  -I"D:/cygwin/lib/gcc/i686-pc-cygwin/3.4.4"\
            -I"D:/cygwin/usr/include" 

main.o: main/main.cpp main/pipi.h
	$(CPP) -c main/main.cpp -o obj/main.o
