# obj: base64.o
# Create by pipi

CPL  = D:/cygwin/bin/
CPP  = $(CPL)g++.exe
ACXXFLAGS =  -I"D:/cygwin/lib/gcc/i686-pc-cygwin/3.4.4"\
            -I"D:/cygwin/usr/include" 

base64.o: base64/base64.cpp base64/base64.h
	$(CPP) -c base64/base64.cpp -o obj/base64.o
