# obj: base64.o
# Create by pipi

CPL  = d:/Dev-Cpp/bin/
CPP  = $(CPL)g++.exe
ACXXFLAGS =  -I"d:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  \
            -I"d:/Dev-Cpp/include/c++/3.4.2/backward"  \
            -I"d:/Dev-Cpp/include/c++/3.4.2/mingw32"  \
            -I"d:/Dev-Cpp/include/c++/3.4.2"  \
            -I"d:/Dev-Cpp/include" 

base64.o: base64/base64.cpp base64/base64.h
	$(CPP) -c base64/base64.cpp -o obj/base64.o $(ACXXFLAGS)
