# obj: aes.o
# Create by pipi

CPL  = D:/cygwin/bin/
CPP  = $(CPL)g++.exe
ACXXFLAGS =  -I"D:/cygwin/lib/gcc/i686-pc-cygwin/3.4.4"\
            -I"D:/cygwin/usr/include" 

aes.o: aes/kaes.cpp aes/kaes.h
	$(CPP) -c aes/kaes.cpp -o obj/aes.o
